name: Workflow 2
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "Te voilà, workflow 2"
